trigger:
 - main
 - feature/*

pool: mypool

stages:
  - stage: Validate
    displayName: Validate
    jobs:
      - job: Validate
        displayName: Validate
        steps:
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'newservice'
              backendAzureRmStorageAccountName: 'pipelinetfstate'
              backendAzureRmContainerName: 'xyzcontainer'
              backendAzureRmKey: 'lab.tfstate'
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'validate'

  - stage: Plan
    displayName: Plan
    jobs:
      - job: Plan
        displayName: Plan
        steps:
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'plan'
              environmentServiceNameAzureRM: 'newservice'

  - stage: Approval
    displayName: Approval
    jobs:
      - job: Approval
        displayName: Approval
        pool: server
        steps:
          - task: ManualValidation@1
            inputs:
              notifyUsers: 'abcascmwlcmlcs'

  - stage: Apply
    dependsOn: Approval
    displayName: Apply
    jobs:
      - job: Apply
        displayName: Apply
        steps:
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'apply'
              environmentServiceNameAzureRM: 'newservice'