trigger:
 branches:
   include:
     - feature/*
     - main

pool: mypool

stages:
  - stage: tfsec
    displayName: tfsec
    jobs:
      - job: 
        displayName: tfsec
        steps:
          - task: AzurePowerShell@5
            inputs:
              azureSubscription: 'newservice'
              ScriptType: 'InlineScript'
              Inline: 'tfsec'

  - stage: tflint
    displayName: tflint
    jobs:
      - job: tflint
        displayName: tflint
        steps:
          - task: PowerShell@2
            inputs:
              targetType: 'inline'
              script: 'tflint --recursive --force'

  - stage: infracost
    displayName: infracost
    jobs:
      - job: infracost
        displayName: infracost
        steps:
          - task: InfracostSetup@2
            inputs:
              apiKey: 'ico-sqro8FlLxZss9ygbGP6Egl2USz9q8Y6Q'
              version: '0.10.x'
  
  - stage: Validate
    displayName: Validate
    jobs:
      - job: Validate
        displayName: Validate
        steps:
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'validate'

  - stage: Plan 
    displayName: Plan Stage
    jobs:
      - job: 
        displayName: Plan job
        steps:
          - task: TerraformInstaller@1
            inputs:
              terraformVersion: 'latest'
          
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'newservice'
              backendAzureRmStorageAccountName: 'bhakuastorage'
              backendAzureRmContainerName: 'bhakuacontainer'
              backendAzureRmKey: 'prod.tfstate'
 


          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'plan'
              environmentServiceNameAzureRM: 'newservice'
          
  - stage: Apply
    condition: and (succeeded () ,eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    displayName: Apply stage
    jobs:
      
      - job: Approval
        displayName: Manual Approval
        pool: server
        steps:
          - task: ManualValidation@1
            inputs:
              notifyUsers: 'ascnja@bcka'

      - job: Apply
        dependsOn: Approval
        displayName: Apply
        steps:
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'newservice'
              backendAzureRmStorageAccountName: 'bhakuastorage'
              backendAzureRmContainerName: 'bhakuacontainer'
              backendAzureRmKey: 'prod.tfstate'
