trigger:
 branches:
   include:
     - feature/*
     - main

pool: mypool

parameters:
  - name: runtfsec
    displayName: run tfsec?
    type: boolean
    default: false

  - name: runtflint
    displayName: run tflint?
    type: boolean
    default: false

  - name: runinfracost
    displayName: run infracost?
    type: boolean
    default: false

stages:
  - stage: tfsec
    condition: ${{ parameters.runtfsec }}
    dependsOn: []
    displayName: tfsec
    jobs:
      - job: 
        displayName: tfsec
        steps:
          - task: PowerShell@2
            inputs:
              targetType: 'inline'
              script: 'tfsec'

  - stage: tflint
    condition: ${{ parameters.runtflint }}
    dependsOn: []
    displayName: tflint
    jobs:
      - job: tflint
        displayName: tflint
        steps:
          - task: PowerShell@2
            inputs:
              targetType: 'inline'
              script: 'tflint --recursive --force'

  - stage: infracost
    condition: ${{ parameters.runinfracost }}
    dependsOn: []
    displayName: infracost
    jobs:
      - job: infracost
        displayName: infracost
        steps:
          - task: InfracostSetup@2
            inputs:
              apiKey: 'ico-sqro8FlLxZss9ygbGP6Egl2USz9q8Y6Q'
              version: '0.10.x'

          - task: PowerShell@2
            displayName: Calculate Infra cost
            inputs:
              targetType: 'inline'
              script: 'infracost breakdown --path .'
  

  - stage: Validate
    dependsOn: []
    displayName: Validate
    jobs:
      - job: Validate
        displayName: Validate
        steps:
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'newservice'
              backendAzureRmResourceGroupName: 'admin_rg'
              backendAzureRmStorageAccountName: 'pipelinetfstate'
              backendAzureRmContainerName: 'xyzcontainer'
              backendAzureRmKey: 'terraform.tfstate'

          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'validate'

  - stage: Plan
    dependsOn:
    - tfsec
    - tflint
    - infracost
    - validate
    displayName: Plan
    jobs:
      - job: Plan
        displayName: Plan
        steps:
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'newservice'
              backendAzureRmResourceGroupName: 'admin_rg'
              backendAzureRmStorageAccountName: 'pipelinetfstate'
              backendAzureRmContainerName: 'xyzcontainer'
              backendAzureRmKey: 'terraform.tfstate'

          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'plan'
              environmentServiceNameAzureRM: 'newservice'

  - stage: Approval
    dependsOn: Plan
    displayName: Approval
    jobs:
      - job: Approval
        displayName: Approval
        pool: server
        steps:
          - task: ManualValidation@1
            inputs:
              notifyUsers: 'sacas'

  - stage: Apply
    dependsOn: Approval
    displayName: Apply
    jobs:
      - job: Apply
        displayName: Apply
        steps:
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'newservice'
              backendAzureRmResourceGroupName: 'admin_rg'
              backendAzureRmStorageAccountName: 'pipelinetfstate'
              backendAzureRmContainerName: 'xyzcontainer'
              backendAzureRmKey: 'terraform.tfstate'

          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'apply'
              environmentServiceNameAzureRM: 'newservice'